### ISSUE TITLE
board_aliases is not working

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#101]
`board_aliases` is not working

``` yml
board_aliases:
  MyTrelloBoard: Fs7boVwI
```

``` console
> vagrant exec bundle exec trollolo get-cards --board-id=MyTrelloBoard
E, [2017-09-14T10:36:17.688401 #4781] ERROR -- : [401 GET https://api.trello.com/1/boards/MyTrelloBoard?lists=open&cards=open&card_checklists=all]: invalid key
/usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/client.rb:99:in `invoke_verb': invalid key (Trello::Error)
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/client.rb:19:in `get'
        from /usr/lib64/ruby/gems/2.4.0/gems/trollolo-0.0.12/lib/trello_wrapper.rb:84:in `get_board'
        from /usr/lib64/ruby/gems/2.4.0/gems/trollolo-0.0.12/lib/trello_wrapper.rb:32:in `retrieve_board_data'
        from /usr/lib64/ruby/gems/2.4.0/gems/trollolo-0.0.12/lib/trello_wrapper.rb:21:in `board'
        from /usr/lib64/ruby/gems/2.4.0/gems/trollolo-0.0.12/lib/cli.rb:96:in `get_cards'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/lib64/ruby/gems/2.4.0/gems/trollolo-0.0.12/bin/trollolo:29:in `<top (required)>'
        from /usr/bin/trollolo:22:in `load'
        from /usr/bin/trollolo:22:in `<main>'
```

**Comment by alexandergraul** [comment]
Will also work on this one.

**Comment by alexandergraul** [comment]
I can't reproduce this bug:
```
$ cat ~/.trollolorc 
---
developer_public_key: XXXXXXXXXXXXXXXXXXXXXXXXXXX
member_token: XXXXXXXXXXXXXXXXX

board_aliases: 
  MyTrelloBoard: 7Zar7bNm
```

``` 
$ bin/trollolo get-cards --board-id=MyTrelloBoard
Burndown Chart
```

**Comment by Ana06** [comment]
@alexandergraul thanks, I will try it again. :wink:
