### ISSUE TITLE
setup-scrum should ask for credentials

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#102]
`setup-scrum` should ask for credentials, as other commands, suchs as `burndown`, are doing.

``` Ruby
> bin/trollolo setup-scrum
E, [2017-09-14T15:15:59.133085 #27956] ERROR -- : [401 POST https://api.trello.com/1/boards]: unauthorized permission requested
/usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/client.rb:99:in `invoke_verb': unauthorized permission requested (Trello::Error)
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/client.rb:24:in `post'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/board.rb:68:in `save'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/basic_data.rb:27:in `save'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/client.rb:67:in `create'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/board.rb:51:in `create'
        from /home/Ana/Documents/trollolo/lib/scrum/creator.rb:16:in `create_sprint_board'
        from /home/Ana/Documents/trollolo/lib/scrum/creator.rb:5:in `create'
        from /home/Ana/Documents/trollolo/lib/cli.rb:323:in `setup_scrum'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from bin/trollolo:29:in `<main>'
```

**Comment by Ana06** [comment]
It is working, my fault :see_no_evil:
