### ISSUE TITLE
trello token expiry notification

### ISSUE THREAD

**Issue by alexandergraul** [openSUSE/trollolo#143]
Currently there is no notification when your trello token (member token) expires. There is just the 
KeyError that is raised when your key is invalid:
```
trollolo burndown                         
/usr/lib64/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)
        from /usr/lib64/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `initialize'
        from /usr/lib64/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `new'
        from /usr/lib64/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/net.rb:29:in `execute_core'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/net.rb:18:in `try_execute'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/net.rb:10:in `execute'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/client.rb:88:in `invoke_verb'
        from /usr/lib64/ruby/gems/2.4.0/gems/ruby-trello-1.5.1/lib/trello/client.rb:19:in `get'
        from /home/alex/github/trollolo/lib/trello_wrapper.rb:84:in `get_board'
        from /home/alex/github/trollolo/lib/trello_wrapper.rb:32:in `retrieve_board_data'
        from /home/alex/github/trollolo/lib/trello_wrapper.rb:21:in `board'
        from /home/alex/github/trollolo/lib/burndown_data.rb:96:in `board'
        from /home/alex/github/trollolo/lib/burndown_data.rb:121:in `get_meta'
        from /home/alex/github/trollolo/lib/burndown_data.rb:100:in `fetch'
        from /home/alex/github/trollolo/lib/burndown_chart.rb:195:in `update'
        from /home/alex/github/trollolo/lib/cli.rb:184:in `burndown'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from bin/trollolo:29:in `<main>'
```
I think there should at least be a hint reminding you that the token only lasts for a month at a time.

**Comment by Ana06** [comment]
and the error even doesn't say that the key is invalid... what that you could already find out that it has expired :thinking:

**Comment by Ana06** [comment]
and it gives the same error as the one in https://github.com/openSUSE/trollolo/issues/139
