### ISSUE TITLE
Sprint lenght "total_days" is integer only

### ISSUE THREAD

**Issue by svollath** [openSUSE/trollolo#75]
Sprint lenght is limited to full days only, since it's an integer.
Normally we start our sprint with a half first day, and end also count the last day half, because of surrounding meetings. This time we started with a full day already, which then sums up in 8.5 days (9.5 for "total_days"). But that's not supported by trollolo currently.
We should change "total_days" to float, in order to support sprints with half a day as well.

yaml snippet:
```
---
meta:
  total_days: 9.5
```

```
> trollolo.ruby2.1 burndown --plot
Traceback (most recent call last):
  File "/usr/lib64/ruby/gems/2.1.0/gems/trollolo-0.0.10/scripts/create_burndown.py", line 74, in <module>
    plot = plot.Plot(data)
  File "/usr/lib64/ruby/gems/2.1.0/gems/trollolo-0.0.10/scripts/plot.py", line 18, in __init__
    self.setXAxisTicks(self.data.total_days)
  File "/usr/lib64/ruby/gems/2.1.0/gems/trollolo-0.0.10/scripts/plot.py", line 54, in setXAxisTicks
    x_labels = range(0, total_days)
TypeError: range() integer end argument expected, got float.
/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3.py:215: Warning: Source ID 7 was not found when attempting to remove it
  GLib.source_remove(self._idle_event_id)
Updated data for sprint 8
```

**Comment by svollath** [comment]
The burndown chart must not support half days, since we'll need one data point per day anyhow - no matter how much time we spent on a specific day.
